"""Build the Company page from page.json and the GFB modules.

Writes two files:
  templates/gfb-companies.html          HubSpot page template: the Home template's canvas, with this
                                        page's modules and field values in its drag-and-drop area.
  preview/gfb-companies-preview.html    Static preview: each module's own module.html rendered with
                                        Jinja2 (close enough to HubL for these modules) and its module.css.

Run:  python3 build_page.py            (preview links the hero photo from Design/Assets)
      python3 build_page.py --embed    (photo embedded, so the preview file works on its own)
"""
import base64, html, json, re, sys
from pathlib import Path

import jinja2

HERE = Path(__file__).resolve().parent
HUBSPOT = HERE.parent.parent                      # Design/HubSpot
HOME = HUBSPOT / "Home" / "code"
PHOTO = HUBSPOT.parent / "Assets" / "Testing assets" / "hero-companies-figma-537x536.jpg"   # Figma 1363:8546
PORTAL_PATH = "/custom/content-mcp/modules/"

# HubSpot module name -> source folder in this repo
SOURCES = {
    "gfb_top_nav": HOME / "gfb-top-nav",
    "gfb_hero_v2": HOME / "gfb-hero",
    "gfb_faq": HOME / "gfb-faq",
    "gfb_final_cta": HOME / "gfb-final-cta",
    "gfb_footer": HOME / "gfb-footer",
    "gfb_match_cards": HERE / "gfb-match-cards",
    "gfb_checklist": HERE / "gfb-checklist",
    "gfb_search_match": HERE / "gfb-search-match",
    "gfb_features": HERE / "gfb-features",
}


def field_defaults(fields):
    """The module's values when nothing is set: each field's default, groups filled from their children."""
    out = {}
    for f in fields:
        if f["type"] == "group" and "occurrence" not in f:
            value = field_defaults(f.get("children", []))
            value.update(f.get("default") or {})
        else:
            value = f.get("default")
        out[f["name"]] = value
    return out


def hubl_literal(value):
    """A HubL literal for a dnd_module argument (HubL reads JSON objects, arrays, strings and booleans)."""
    return json.dumps(value, ensure_ascii=False)


def build_template(page):
    home = (HOME / "templates" / "gfb-home.html").read_text()
    sections = []
    for m in page["modules"]:
        args = "".join(f", {k}={hubl_literal(v)}" for k, v in m.get("fields", {}).items())
        sections.append(
            '        {% dnd_section full_width=true, padding={"top": 0, "bottom": 0, "left": 0, "right": 0} %}\n'
            f'          {{% dnd_module path="{PORTAL_PATH}{m["module"]}"{args} %}}{{% end_dnd_module %}}\n'
            "        {% end_dnd_section %}")
    area = (f'{{% dnd_area "main" label="{page["dnd_label"]}" %}}\n' + "\n".join(sections) + "\n      {% end_dnd_area %}")
    out = re.sub(r'\{% dnd_area "main".*?\{% end_dnd_area %\}', lambda _: area, home, count=1, flags=re.S)
    out = out.replace("label: GFB Home", f"label: {page['label']}", 1)
    # reveal the new modules' cards and rows one after another, like the Home modules' items
    out = out.replace("'.gfb-wyg__card, ", "'.gfb-wyg__card, .gfb-mc__card, .gfb-chk__item, .gfb-ftrs__item, ", 1)
    header = ("{# Generated by ../build_page.py from ../page.json. Edit page.json or the modules, then rebuild. #}\n")
    out = out.replace("<!doctype html>", header + "<!doctype html>", 1)
    return out


class HublEnvironment(jinja2.Environment):
    """HubL reads module.items as the field "items"; plain Jinja2 would find dict.items first."""
    def getattr(self, obj, attribute):
        if isinstance(obj, dict) and attribute in obj:
            return obj[attribute]
        return super().getattr(obj, attribute)


def build_preview(page, photo_src):
    env = HublEnvironment(extensions=["jinja2.ext.do"], autoescape=False, undefined=jinja2.ChainableUndefined)
    env.filters["escape_url"] = lambda s: html.escape(str(s or ""), quote=True)
    env.filters["escape_attr"] = lambda s: html.escape(str(s or ""), quote=True)
    env.filters["escape"] = lambda s: html.escape(str(s or ""), quote=False)
    env.filters["sanitize_html"] = lambda s: s
    env.globals["require_css"] = lambda *a, **k: ""

    css, body = [], []
    for i, m in enumerate(page["modules"]):
        src = SOURCES[m["module"]]
        module = field_defaults(json.loads((src / "fields.json").read_text()))
        module.update(m.get("fields", {}))
        if m["module"] == "gfb_hero_v2":
            module["photo"] = dict(module.get("photo") or {}, src=photo_src, width=537, height=536)
        tpl = env.from_string((src / "module.html").read_text())
        body.append(tpl.render(module=module, name=f"module_{i}", request={"path": page["request_path"]}))
        style = (src / "module.css").read_text()
        if style not in css:
            css.append(style)

    head = (HOME / "templates" / "gfb-home.html").read_text()
    fonts = re.search(r'<link rel="preconnect".*?display=swap">', head, flags=re.S).group(0)
    canvas = re.search(r"<style>\s*/\* GFB Home canvas.*?</style>", head, flags=re.S).group(0)
    return ("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
            "<title>GoFindBuild Companies Page</title>\n"
            "<!-- Generated by ../build_page.py from ../page.json and the GFB modules. Do not edit by hand. -->\n"
            f"{fonts}\n{canvas}\n<style>\n" + "\n".join(css) + "\n</style>\n</head>\n<body>\n"
            "<main class=\"gfb-page\" id=\"main-content\">\n" + "\n".join(body) + "\n</main>\n</body>\n</html>\n")


def main():
    page = json.loads((HERE / "page.json").read_text())
    (HERE / "templates" / "gfb-companies.html").write_text(build_template(page))
    if "--embed" in sys.argv:
        photo_src = "data:image/jpeg;base64," + base64.b64encode(PHOTO.read_bytes()).decode()
    else:
        photo_src = "../../../../Assets/Testing%20assets/" + PHOTO.name
    out = HERE / "preview" / "gfb-companies-preview.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(build_preview(page, photo_src))
    print("wrote", (HERE / "templates" / "gfb-companies.html").relative_to(HUBSPOT), "and", out.relative_to(HUBSPOT))


if __name__ == "__main__":
    main()
